pipeline:
  build:
    image: golang:1.14
    environment:
      - GOPATH=/drone
    commands:
      - go test ./pkg/...

  docker-push:
    when:
      event: push
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/sqs-autoscaler-controller
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_SHA:0:8}

  docker-tagged:
    when:
      event: tag
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/sqs-autoscaler-controller
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
