kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: sqs-autoscaler-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqs-autoscaler-controller
      annotations:
        iam.amazonaws.com/role: cloud_sqs_autoscaler
    spec:
      volumes:
        - name: ssl-certs
          hostPath:
            path: /usr/share/ca-certificates
      containers:
      - image: registry.usw.co/cloud/sqs-autoscaler-controller:latest
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
          - --statsd=$(NODE_NAME):30565
        name: sqs-autoscaler-controller
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
