apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sqs-autoscaler-controller
  name: sqs-autoscaler-controller
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sqs-autoscaler-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: cloud_sqs_autoscaler
      creationTimestamp: null
      labels:
        app: sqs-autoscaler-controller
    spec:
      containers:
      - args:
        - --statsd=$(NODE_NAME):30565
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/uswitch/sqs-autoscaler-controller:master
        imagePullPolicy: Always
        name: sqs-autoscaler-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
          type: ""
        name: ssl-certs
status: {}
