apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: sqs-autoscaler-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: sqs-autoscaler-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sqs-autoscaler-controller-role
subjects:
- kind: ServiceAccount
  name: sqs-autoscaler-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: kube-system
  name: sqs-autoscaler-controller-role
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - "aws.uswitch.com"
  resources:
  - sqsautoscalers
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - update
